"""add route_stops, time windows to orders

Revision ID: 10a95ef0b258
Revises: 01ec499e8eae
Create Date: 2026-08-28 19:36:16.772357
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a95ef0b258'
down_revision: Union[str, None] = '01ec499e8eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time_window_start', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('time_window_end', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('service_time_min', sa.Integer(), nullable=True))

    # Tabla de paradas de ruta (OPT-13): cada orden es una parada dentro de
    # una ruta, con su secuencia y métricas asociadas.
    op.create_table(
        'route_stops',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('route_id', sa.Integer(), sa.ForeignKey('routes.id'), nullable=False),
        sa.Column('order_id', sa.Integer(), sa.ForeignKey('orders.id'), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
        sa.Column('distance_from_previous_km', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pendiente'),
    )
    op.create_index(op.f('ix_route_stops_id'), 'route_stops', ['id'], unique=False)
    op.create_index(
        op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False
    )

    # Migración de datos: crea las filas route_stops a partir de las rutas
    # existentes que guardan sus paradas en la columna JSON `stops`.
    # `stops` es una lista de objetos con {order_id, sequence} (o llaves
    # equivalentes), ordenada según su secuencia.
    op.execute("""
        INSERT INTO route_stops (route_id, order_id, sequence, status)
        SELECT
            r.id,
            (elem->>'order_id')::int,
            COALESCE((elem->>'sequence')::int, ord - 1),
            'pendiente'
        FROM routes r,
             jsonb_array_elements(
                 COALESCE(r.stops::jsonb, '[]'::jsonb)
             ) WITH ORDINALITY AS t(elem, ord)
        WHERE r.stops IS NOT NULL
          AND jsonb_typeof(r.stops::jsonb) = 'array'
          AND (elem->>'order_id') IS NOT NULL
    """)

    # NOTA (OPT-13): la columna `routes.stops` se conserva como snapshot de
    # compatibilidad con el frontend actual. Se eliminará en Sprint 4 cuando
    # el frontend lea exclusivamente de route_stops.


def downgrade() -> None:
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_column('orders', 'service_time_min')
    op.drop_column('orders', 'time_window_end')
    op.drop_column('orders', 'time_window_start')
    # ### end Alembic commands ###
